platform :ios, '12.0'

ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  # Use environment variable first
  if ENV['FLUTTER_ROOT']
    return ENV['FLUTTER_ROOT']
  end
  
  # Try to find from common paths
  possible_roots = [
    '/opt/hostedtoolcache/flutter/stable-3.24.5-x64/flutter',
    '/opt/hostedtoolcache/flutter/stable-3.24.5-arm64/flutter',
    '/Users/runner/hostedtoolcache/flutter/stable-3.24.5-arm64/flutter',
    '/usr/local/flutter',
    '/opt/flutter'
  ]
  
  possible_roots.each do |root|
    if File.directory?(root)
      return root
    end
  end
  
  raise "FLUTTER_ROOT not found. Please set FLUTTER_ROOT environment variable."
end

# Try to find and load podhelper
podhelper_loaded = false
[
  File.join(flutter_root, 'packages', 'flutter_tools', 'bin', 'podhelper'),
  '/opt/hostedtoolcache/flutter/stable-3.24.5-x64/flutter/packages/flutter_tools/bin/podhelper',
  '/opt/hostedtoolcache/flutter/stable-3.24.5-arm64/flutter/packages/flutter_tools/bin/podhelper',
  '/Users/runner/hostedtoolcache/flutter/stable-3.24.5-arm64/flutter/packages/flutter_tools/bin/podhelper'
].each do |path|
  if File.exist?(path + '.rb')
    require path
    podhelper_loaded = true
    break
  end
end

# If podhelper not found, define minimal setup
unless podhelper_loaded
  def flutter_ios_podfile_setup
    # Minimal setup
  end
  
  def flutter_install_all_ios_pods(installation_root)
    # Minimal setup
  end
end

target 'Runner' do
  use_frameworks!
  use_modular_headers!
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
    end
  end
end
